### ISSUE TITLE
Fog is disabled

### ISSUE THREAD

**Issue by mineland-0066** [TopchetoEU/animated-chunks#16]
Fog effects are disabled for some reason. Looking at the original mod it doesnt seem to be the case, and it also means water fog is disabled, except on entities for some reason. dont think thats supposed to happen
![image](https://user-images.githubusercontent.com/60583383/194451254-603072ea-903f-4cdd-875f-458729e04b9b.png)

not sure if its a side effect with another mod, but adding this to my main install they get disabled

**Comment by TopchetoEU** [comment]
it is not a side effect, i will try and fix it. thanks for logging an issue!

**Comment by TopchetoEU** [comment]
Fixed it :)
